enum ERROR_CODES {
  INVALID_ACCESS_TOKEN = "INVALID_ACCESS_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

export default ERROR_CODES;
